version: 2
updates:
  - package-ecosystem: 'yarn'
    directory: '/frontend'
    schedule:
      interval: 'weekly'
    target-branch: 'dev'

  - package-ecosystem: 'pip'
    directory: '/backend'
    schedule:
      interval: 'weekly'
    target-branch: 'dev'